style:
  NewLineAtEndOfFile:
    active: false
  ExplicitItLambdaParameter:
    active: false


complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true

    
formatting:
  FinalNewline:
    active: false
  Indentation:
    active: false
  ImportOrdering:
    active: false
  Wrapping:
    active: false
  ArgumentListWrapping:
    active: false
  NoEmptyFirstLineInMethodBlock:
    active: false


naming:
  VariableNaming:
    active: false


performance:
  SpreadOperator:
    active: false

